[tool.poetry]
name = "starbuzz"
version = "0.1.0"
description = "Star Buzz"
authors = ["Camila Gomes <7camilagomes@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
